//
//  MainModuleRouter.swift
//  ApiTestMobile
//
//  Created ISAAC DAVID SANTIAGO on 15/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainModuleRouter: MainModuleWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MainModuleViewController(nibName: nil, bundle: nil)
        let interactor = MainModuleInteractor()
        let router = MainModuleRouter()
        let presenter = MainModulePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
