//
//  MainModuleInteractor.swift
//  ApiTestMobile
//
//  Created ISAAC DAVID SANTIAGO on 15/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainModuleInteractor: MainModuleInteractorProtocol {

    weak var presenter: MainModulePresenterProtocol?
}
