//
//  MainModuleProtocols.swift
//  ApiTestMobile
//
//  Created ISAAC DAVID SANTIAGO on 15/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainModuleWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainModulePresenterProtocol: class {

}

//MARK: Interactor -
protocol MainModuleInteractorProtocol: class {

  var presenter: MainModulePresenterProtocol?  { get set }
}

//MARK: View -
protocol MainModuleViewProtocol: class {

  var presenter: MainModulePresenterProtocol?  { get set }
}
