//
//  MainModulePresenter.swift
//  ApiTestMobile
//
//  Created ISAAC DAVID SANTIAGO on 15/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainModulePresenter: MainModulePresenterProtocol {

    weak private var view: MainModuleViewProtocol?
    var interactor: MainModuleInteractorProtocol?
    private let router: MainModuleWireframeProtocol

    init(interface: MainModuleViewProtocol, interactor: MainModuleInteractorProtocol?, router: MainModuleWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
