//
//  MainModuleViewController.swift
//  ApiTestMobile
//
//  Created ISAAC DAVID SANTIAGO on 15/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainModuleViewController: UIViewController, MainModuleViewProtocol {

	var presenter: MainModulePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
